### ISSUE TITLE
Create Wall Handler for Tile Variants

### ISSUE THREAD

**Issue by aaron-jencks** [aaron-jencks/Telnet-Mud#14]
Should require variants with names:
* TLC - Top Left Corner
* TRC - Top Right Corner
* V - Vertical
* H - Horizontal
* BLC - Bottom Left Corner
* BRC - Bottom Right Corner
* UT - Up T
* RT - Right T
* LT - Left T
* DT - Down T
* Cross - Center Cross

In the Variant Table for the given variant ID

**Comment by iggy12345** [comment]
This is blocked by #42
